### ISSUE TITLE
Not rerender if using streambuilder

### ISSUE THREAD

**Issue by NaufalHafizi** [thecodepapaya/show_up_animation#1]

**Comment by thecodepapaya** [comment]
Could you provide a minimal code to replicate the issue you are facing?

**Comment by NaufalHafizi** [comment]
I used streambuilder for firebase, the stream was fired. but the widget not rerender. This is my code

StreamBuilder(
  stream: Firestore.instance
  .collection("item")
  .snapshots(),

  builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot){
    if(snapshot.connectionState == ConnectionState.waiting) {
      return Container(
        child: Center(
          child: CircularProgressIndicator(),
        ),
      );
    } else {
      if((snapshot.data.documents).length == 0){
        return Center(child: Text("No Item"),);
      } else {
        return MediaQuery.removePadding(
          context: context,
          removeTop: true,
          child: SingleChildScrollView(
            scrollDirection: Axis.vertical,
            child: ShowUpList(
              direction: Direction.vertical,
              animationDuration: Duration(milliseconds: 500),
              delayBetween: Duration(milliseconds: 200),
              offset: -0.2,
              children: listItem(context, snapshot.data.documents)
            ),
          )
        );
      }
      
    }
  },
)

listItem(context,document){

  List<Widget> listwidget = [];
  
  for(int i = 0; i < document.length; i++){
    listwidget.add(
      Text(document[i]['name'])
    );
  }

  return listwidget;
  
}

Thank you

**Comment by thecodepapaya** [comment]
Hello @NaufalHafizi, 
Thank you for reporting the issue. However, the issue is not related to the plugin but rather the framework itself. You can solve the above problem by providing your children with a `Unique Key()` so that the widget is rebuilt on every callback from the stream.
I was able to solve this particular problem by adding a `Unique Key()` to the `key` parameter in the `MediaQuery.removePadding()` constructor. Take a look below for a similar code reproducing the above behaviour.
```
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:show_up_animation/show_up_animation.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  StreamController<int> str = StreamController<int>();
  StreamSink<int> strsink;
  Stream<int> stream;
  var rnd = Random();

  @override
  void initState() {
    super.initState();
    strsink = str.sink;
    stream = str.stream;
  }

  @override
  void dispose() {
    str.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: StreamBuilder<int>(
          stream: stream,
          builder: (BuildContext context, AsyncSnapshot<int> snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return Container(
                child: Center(
                  child: CircularProgressIndicator(),
                ),
              );
            } else {
              if (snapshot.data == 0) {
                return Center(
                  child: Text("No Item"),
                );
              } else {
                print("Rendering: ${snapshot.data}");
                return MediaQuery.removePadding(
                  key: UniqueKey(), // you need to add a unique key here to help the framwork differentiate the widgets on stream events
                  context: context,
                  removeTop: true,
                  child: SingleChildScrollView(
                    scrollDirection: Axis.vertical,
                    child: new ShowUpList(
                      direction: Direction.vertical,
                      animationDuration: Duration(milliseconds: 500),
                      delayBetween: Duration(milliseconds: 200),
                      offset: -0.2,
                      children: listItem(snapshot.data),
                    ),
                  ),
                );
              }
            }
          },
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          int num = rnd.nextInt(20);
          print("Generated: $num");
          strsink.add(num);
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

listItem(int len) {
  List<Widget> listwidget = [];
  for (int i = 0; i < len; i++) {
    listwidget.add(Text("iteration $i"));
  }
  return listwidget;
}
```
However, I will add a `key` parameter to the plugin widget as well in future so that these issues become easier to resolve.
Regards,
Ashutosh Singh

**Comment by NaufalHafizi** [comment]
wow it's working now. thank you for the reply and the package
