### ISSUE TITLE
widgets inside the showuplist can't be changed 

### ISSUE THREAD

**Issue by AZZ404** [thecodepapaya/show_up_animation#2]
i am using a text widget that changes its content every period of time but it stopped working when i putted it inside showuplist animation

**Comment by thecodepapaya** [comment]
Can you please share a code snippet to replicate the problem you are facing?

**Comment by thecodepapaya** [comment]
Closed because of no response.

**Comment by bluejeans117** [comment]
Hey, I can second this issue. Here's a sample code snippet:

IgnorePointer(
                          ignoring: hasValue,
                          child: DropdownButtonFormField<String>(
                              focusNode: focusNode,
                              isExpanded: true,
                              value: dropValue,
                              onChanged: (String newValue) {
                                setState(() {
                                  dropValue = newValue;
                                });
                              },
                              items: [
                                'A',
                                'B',
                                'C',
                                'D',
                                'E'
                              ].map<DropdownMenuItem<String>>((String value) {
                                return DropdownMenuItem<String>(
                                  value: value,
                                  child: Text(value),
                                );
                              }).toList()))

this is placed under a ShowUpList as one of the children. Maybe you could tell me what I'm doing wrong?
