### ISSUE TITLE
Null safety?

### ISSUE THREAD

**Issue by guidospadavecchia** [thecodepapaya/show_up_animation#5]
Our team is a few packages away from **null-safety** migration for our app. Any chance to migrate this package?

**Comment by thecodepapaya** [comment]
Hello
Yes I've been working on migrating the package towards null safety. You'll likely get an update in a few days.

**Comment by thecodepapaya** [comment]
The null safe version has been published in the latest commit [3bb0713](https://github.com/thecodepapaya/show_up_animation/commit/3bb07137877a5039b780b1f7625def997f5b223c) and is now available as a prerelease at [pub.dev](https://pub.dev/packages/show_up_animation/versions/2.0.0-nullsafety.0/changelog)

**Comment by guidospadavecchia** [comment]
Thanks!
